version: "3.9"
services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "${MINIO_PORT}:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    volumes:
      - ./tmp/minio:/data
    command: ["server", "/data","--console-address", ":9001"]
    networks:
      - mego_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mego_storage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mego_storage
    depends_on:
      minio:
        condition: service_healthy
    ports:
      - "${STORAGE_SERVICE_SERVER_PORT}:${STORAGE_SERVICE_SERVER_PORT}"
    networks:
      - mego_network

networks:
  mego_network:
    external: true